### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by HybridDog** [Git-Lit/000002678#1]
https://git-lit.github.io/000002678 (Read the book here.) doesn't work

**Comment by JonathanReeve** [comment]
Thanks for pointing this out, HybridDog. It looks like books that include colons break the _config.yml YAML, which causes github.io to be unable to build the page. Seems like an easy fix.

**Comment by JonathanReeve** [comment]
Probably fixed in https://github.com/Git-Lit/git-lit/commit/7500cc43ff02b5a4b446203a4bf48474492d8ad5.

**Comment by HybridDog** [comment]
Looks like title can't contain `"`

**Comment by JonathanReeve** [comment]
Thanks for the heads-up. I'll close this issue in favor of https://github.com/Git-Lit/git-lit/issues/59, and continue to track this issue there.
